apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy4
  labels:
    app: autodeploy4
  namespace: namespace-workflow-1710481482250
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy4
  template:
    metadata:
      labels:
        app: autodeploy4
    spec:
      containers:
        - name: autodeploy4
          image: acrworkflow1710481482250.azurecr.io/image-workflow-1710481482250:latest
          ports:
            - containerPort: 5000